CREATE TABLE IF NOT EXISTS projects
(
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    code       VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_project PRIMARY KEY (project_id),
    CONSTRAINT UQ_name_code UNIQUE (name, code)
);

CREATE TABLE IF NOT EXISTS object_pir
(
    object_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    project_id       BIGINT                                  NOT NULL,
    parent_object_id BIGINT,
    CONSTRAINT pk_object PRIMARY KEY (object_id),
    CONSTRAINT fk_project_to_object FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT fk_parent_id FOREIGN KEY (parent_object_id) REFERENCES object_pir (object_id),
    CONSTRAINT UQ_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS documentation_rd
(
    documentation_rd_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stamp               VARCHAR(255)                            NOT NULL,
    number              BIGINT                                  NOT NULL,
    object_id           BIGINT                                  NOT NULL,
    CONSTRAINT pk_object PRIMARY KEY (documentation_rd_id),
    CONSTRAINT fk_object_to_documentation FOREIGN KEY (object_id) REFERENCES object_pir (object_id)
);

CREATE TABLE IF NOT EXISTS documentation_pd
(
    documentation_pd_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stamp               VARCHAR(255)                            NOT NULL,
    number              BIGINT                                  NOT NULL,
    project_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_documentation_pd_id PRIMARY KEY (documentation_pd_id),
    CONSTRAINT fk_project_to_documentation FOREIGN KEY (project_id) REFERENCES projects (project_id)
);